const reports = [
  {
    id: "RPT-120",
    title: "Barangay Summary - May",
    type: "Barangay Report",
    generatedBy: "PDAO Admin",
    date: "May 28, 2026",
  },
  {
    id: "RPT-121",
    title: "Disability Classification Overview",
    type: "Disability Report",
    generatedBy: "PDAO Analytics",
    date: "May 26, 2026",
  },
  {
    id: "RPT-122",
    title: "Subsidy Distribution Summary",
    type: "Subsidy Report",
    generatedBy: "PDAO Finance",
    date: "May 25, 2026",
  },
];

export default function Reports() {
  return (
    <div className="space-y-6">
      <section className="gov-card rounded-2xl p-6">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[color:var(--gov-muted)]">
              Reports Center
            </p>
            <h2 className="text-xl font-semibold">Generate PDAO Reports</h2>
            <p className="mt-2 text-sm text-[color:var(--gov-muted)]">
              Export barangay, disability, demographic, and subsidy reports.
            </p>
          </div>
          <button
            type="button"
            className="rounded-full bg-[color:var(--gov-primary)] px-4 py-2 text-xs font-semibold text-white transition hover:-translate-y-0.5"
          >
            New Report
          </button>
        </div>
      </section>

      <section className="gov-card rounded-2xl p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex flex-wrap gap-3">
            <select className="rounded-full border border-[color:var(--gov-border)] bg-[color:var(--gov-surface)] px-4 py-2 text-sm">
              <option>All report types</option>
              <option>Barangay Report</option>
              <option>Disability Report</option>
              <option>Demographic Report</option>
              <option>Subsidy Report</option>
            </select>
            <input
              type="date"
              className="rounded-full border border-[color:var(--gov-border)] bg-[color:var(--gov-surface)] px-4 py-2 text-sm"
            />
          </div>
          <button
            type="button"
            className="rounded-full border border-[color:var(--gov-border)] px-4 py-2 text-xs font-semibold"
          >
            Export CSV/PDF
          </button>
        </div>

        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="text-xs uppercase text-[color:var(--gov-muted)]">
              <tr>
                <th className="pb-3">Report ID</th>
                <th className="pb-3">Title</th>
                <th className="pb-3">Type</th>
                <th className="pb-3">Generated by</th>
                <th className="pb-3">Date</th>
                <th className="pb-3">Action</th>
              </tr>
            </thead>
            <tbody className="text-[color:var(--gov-text)]">
              {reports.map((row) => (
                <tr key={row.id} className="border-t border-[color:var(--gov-border)]">
                  <td className="py-3">{row.id}</td>
                  <td className="py-3">{row.title}</td>
                  <td className="py-3">{row.type}</td>
                  <td className="py-3">{row.generatedBy}</td>
                  <td className="py-3">{row.date}</td>
                  <td className="py-3">
                    <button
                      type="button"
                      className="text-xs font-semibold text-[color:var(--gov-accent)]"
                    >
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
