import loretoSeal from "../assets/loreto_seal.jpg";

const toDataUrl = async (url) => {
  const res = await fetch(url);
  const blob = await res.blob();
  return await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

// rows: [{ name, municipality, barangay, item, qty, status, detail }]
// status is "Claimed" | "Unclaimed" | "No assistance yet".
export async function exportAssistancePdf(rows, scopeText = "", municipalityScope = null) {
  const headerLocality = municipalityScope
    ? `Municipality of ${municipalityScope}`
    : "Province of Agusan del Sur";
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const centerX = pageWidth / 2;

  // ---- Header ----
  let sealData = null;
  try {
    sealData = await toDataUrl(loretoSeal);
  } catch {
    // header still renders without the seal
  }
  doc.setFontSize(11);
  const repLines = [
    { text: "Republic of the Philippines", font: "normal" },
    { text: "PROVINCE OF AGUSAN DEL SUR", font: "bold" },
    { text: headerLocality, font: "bold" },
  ];
  let maxTextW = 0;
  repLines.forEach((l) => {
    doc.setFont("helvetica", l.font);
    maxTextW = Math.max(maxTextW, doc.getTextWidth(l.text));
  });
  const logoW = 46;
  const logoX = centerX - maxTextW / 2 - 12 - logoW;
  if (sealData) doc.addImage(sealData, "JPEG", logoX, 24, logoW, logoW);

  doc.setFont("helvetica", "normal");
  doc.text("Republic of the Philippines", centerX, 36, { align: "center" });
  doc.setFont("helvetica", "bold");
  doc.text("PROVINCE OF AGUSAN DEL SUR", centerX, 50, { align: "center" });
  doc.text(headerLocality, centerX, 64, { align: "center" });
  doc.setFontSize(12);
  doc.text("Persons with Disability Affairs Office (PDAO)", centerX, 84, {
    align: "center",
  });
  doc.text("PWD ASSISTANCE / SUBSIDY RECORD", centerX, 100, { align: "center" });

  if (scopeText) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text(scopeText, centerX, 114, { align: "center" });
    doc.setFont("helvetica", "normal");
  }

  // ---- Totals summary ----
  const claimed = rows.filter((r) => r.status === "Claimed").length;
  const unclaimed = rows.filter((r) => r.status === "Unclaimed").length;
  const pwds = new Set(rows.map((r) => r.name)).size;
  doc.setFontSize(9.5);
  doc.text(
    `PWDs: ${pwds}   •   Claimed: ${claimed}   •   Unclaimed: ${unclaimed}`,
    centerX,
    scopeText ? 128 : 118,
    { align: "center" }
  );

  // ---- Table ----
  const body = rows.map((r, i) => [
    i + 1,
    r.name || "—",
    r.municipality || "—",
    r.barangay || "—",
    r.item || "—",
    r.qty === "" || r.qty == null ? "" : String(r.qty),
    r.status,
    r.detail || "",
  ]);

  autoTable(doc, {
    startY: scopeText ? 138 : 128,
    head: [
      ["#", "PWD Name", "Municipality", "Barangay", "Item / Assistance", "Qty", "Status", "Date / Receipt"],
    ],
    body,
    styles: { fontSize: 8.5, cellPadding: 4 },
    headStyles: { fillColor: [30, 64, 175], textColor: 255, halign: "center" },
    columnStyles: {
      0: { halign: "center", cellWidth: 22 },
      5: { halign: "center", cellWidth: 30 },
      6: { halign: "center", cellWidth: 62 },
    },
    // Colour the status cell: green claimed, amber unclaimed, grey none.
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 6) {
        const v = data.cell.raw;
        if (v === "Claimed") data.cell.styles.textColor = [21, 128, 61];
        else if (v === "Unclaimed") data.cell.styles.textColor = [180, 83, 9];
        else data.cell.styles.textColor = [120, 120, 120];
      }
    },
  });

  const asOf = new Date().toLocaleString("en-PH", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by the CMSPD portal on ${asOf}.`,
    centerX,
    doc.internal.pageSize.getHeight() - 20,
    { align: "center" }
  );

  doc.save(`pwd-assistance-record-${Date.now()}.pdf`);
}
