import loretoSeal from "../assets/loreto_seal.jpg";

// Load an imported image URL as a data URL so jsPDF can embed it.
const toDataUrl = async (url) => {
  const res = await fetch(url);
  const blob = await res.blob();
  return await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

const fmtDateTime = (iso) =>
  iso
    ? new Date(iso).toLocaleString("en-PH", {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "numeric",
        minute: "2-digit",
      })
    : "";

// Generate + download an official acknowledgement receipt for one recipient.
// data: { receiptNumber, receivedAt, fullName, pwdId, barangay, item, quantity }
export async function exportReceiptPdf(data) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const centerX = pageWidth / 2;
  const left = 56;
  const right = pageWidth - 56;

  // ---- Header: seal beside centered republic block ----
  let sealData = null;
  try {
    sealData = await toDataUrl(loretoSeal);
  } catch {
    // header still renders without the seal
  }

  doc.setFontSize(11);
  const repLines = [
    { text: "Republic of the Philippines", font: "normal" },
    { text: "Province of Agusan del Sur", font: "normal" },
    { text: "Municipality of Loreto", font: "bold" },
  ];
  let maxTextW = 0;
  repLines.forEach((l) => {
    doc.setFont("helvetica", l.font);
    maxTextW = Math.max(maxTextW, doc.getTextWidth(l.text));
  });
  const logoW = 52;
  const gap = 14;
  const logoX = centerX - maxTextW / 2 - gap - logoW;
  if (sealData) doc.addImage(sealData, "JPEG", logoX, 44, logoW, logoW);

  doc.setFont("helvetica", "normal");
  doc.text("Republic of the Philippines", centerX, 56, { align: "center" });
  doc.text("Province of Agusan del Sur", centerX, 71, { align: "center" });
  doc.setFont("helvetica", "bold");
  doc.text("Municipality of Loreto", centerX, 86, { align: "center" });

  doc.setFontSize(12);
  doc.text("PERSONS WITH DISABILITY AFFAIRS OFFICE (PDAO)", centerX, 108, {
    align: "center",
  });

  // ---- Title ----
  doc.setFontSize(16);
  doc.text("ACKNOWLEDGEMENT RECEIPT", centerX, 140, { align: "center" });

  // ---- Receipt no. + date ----
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Receipt No: ${data.receiptNumber || "—"}`, left, 168);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${fmtDateTime(data.receivedAt)}`, right, 168, { align: "right" });

  // ---- Details box ----
  const boxTop = 186;
  const rowH = 30;
  const rows = [
    ["Beneficiary (PWD)", data.fullName || "—"],
    ["PWD ID No.", data.pwdId || "—"],
    ["Barangay", data.barangay || "—"],
    ["Item / Assistance", data.item || "—"],
    ["Quantity", String(data.quantity ?? 1)],
  ];
  const boxH = rowH * rows.length;
  const labelW = 150;

  doc.setDrawColor(120, 120, 120);
  doc.setLineWidth(0.7);
  doc.rect(left, boxTop, right - left, boxH);
  rows.forEach((r, i) => {
    const y = boxTop + i * rowH;
    if (i > 0) doc.line(left, y, right, y);
    doc.line(left + labelW, y, left + labelW, y + rowH);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(r[0], left + 10, y + rowH / 2 + 3);
    doc.setFont("helvetica", "normal");
    doc.text(String(r[1]), left + labelW + 10, y + rowH / 2 + 3, {
      maxWidth: right - (left + labelW) - 20,
    });
  });

  // ---- Statement ----
  const stmtY = boxTop + boxH + 28;
  doc.setFontSize(10.5);
  const statement =
    "This certifies that the above-named person with disability has received the assistance/item " +
    "indicated above from the Persons with Disability Affairs Office (PDAO), Municipality of Loreto, " +
    "Agusan del Sur.";
  doc.text(doc.splitTextToSize(statement, right - left), left, stmtY);

  // ---- Signatures ----
  const sigY = stmtY + 90;
  const colW = (right - left) / 2;
  doc.setLineWidth(0.7);
  doc.line(left, sigY, left + colW - 24, sigY);
  doc.line(left + colW + 4, sigY, right, sigY);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(data.fullName || "Beneficiary", left, sigY + 14);
  doc.text("PDAO Officer", left + colW + 4, sigY + 14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 90, 90);
  doc.text("Received by (signature over printed name)", left, sigY + 27);
  doc.text("Released by (signature over printed name)", left + colW + 4, sigY + 27);
  doc.setTextColor(0, 0, 0);

  // ---- Footer note ----
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by the CMSPD portal on ${fmtDateTime(new Date().toISOString())}. ` +
      "Keep this receipt as proof of assistance received.",
    centerX,
    doc.internal.pageSize.getHeight() - 48,
    { align: "center", maxWidth: right - left }
  );

  const slug = (data.receiptNumber || "receipt").replace(/[^A-Za-z0-9-]/g, "");
  doc.save(`${slug}.pdf`);
}

// Convenience: build the receipt payload from a recipient row + its profile and
// the parent announcement/event, then generate the PDF.
export async function exportRecipientReceipt(recipient, { item } = {}) {
  const profile = recipient.profile ?? {};
  await exportReceiptPdf({
    receiptNumber: recipient.receipt_number,
    receivedAt: recipient.received_at,
    fullName: profile.full_name,
    pwdId: profile.pwd_id_number,
    barangay: profile.barangay,
    item: item || "Assistance",
    quantity: recipient.quantity,
  });
}
